### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by SamGG** [markrobinsonuzh/cytofWorkflow#15]
Hi,
I noticed that the vignette refers to uwot as github, but the package is officially on CRAN as you know.
https://github.com/markrobinsonuzh/cytofWorkflow/blob/9762d03875b2d2d067e1f0c36d5ad42511c9645a/vignettes/cytofWorkflow.Rmd#L131
BTW, Burkhard Becher does not got any affiliation.
I didn't find why uwot is listed in the Depends of DESCRIPTION whereas it is not in the NAMESPACE.
Keep safe,
SAmuel

**Comment by markrobinsonuzh** [comment]
Great, thanks.

Just checked in a change to both release (3.11) and devel to fix the affiliation and the CRAN package link.

I think we put `uwot` in Depends, because it is needed by `scater`.
