### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by 83years** [markrobinsonuzh/cytofWorkflow#22]
Hi, 

I'm running the script as laid out in the [vignette](https://bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html) and three of the flow parameters don't want to run. 

I create the md object using:
`file_name<-as.character(pData(fs)$name)
sample_id<- as.character(pData(fs)$name)
condition<- c("Tube1","Tube2","Tube1","Tube2","Tube1","Tube2","Tube1","Tube2","Tube1","Tube2","Tube1","Tube2")
patient_id<- c("Donor_1","Donor_1","Donor_2","Donor_2","Donor_3","Donor_3","Donor_4","Donor_4","Donor_5","Donor_5","Donor_6","Donor_6")
md<-data.frame(cbind(file_name, sample_id, condition, patient_id))
head(md)`

I then make the panel using:
`fcs_colname <-colnames(fs)
antigen <- c("FSC-A","FSC-H","SSC-A","SSC-H",
             "CD196", "CD25", 
             "CD16", "CCR10", "CD62L", "CD4",
             "HLADR", "CD8", "CD45RA", "CD19", "CD95", "CD194", "CD3IgD",
             "PD1", "CD161", "CD28", "CD57", "CD38", "va72TCR", "CD127", "CD27",
             "gdTCR", "CD56", "CD185", "CD183", "CCR7",
             "Time")
marker_class <- c(rep("none",4),rep("type",26),"none")
panel<- data.frame(cbind(fcs_colname, antigen, marker_class))
head(panel)`

The output from head(panel) is:
`       fcs_colname antigen marker_class
1             FSC-A   FSC-A         none
2             FSC-H   FSC-H         none
3             SSC-A   SSC-A         none
4             SSC-H   SSC-H         none
5      FJComp-APC-A   CD196         type
6 FJComp-APC-R700-A    CD25         type`

The output of `all(panel$fcs_colname %in% colnames(fs))` is TRUE

The sce is made with:
`sce <- prepData(fs, panel, md, features = panel$fcs_colname,cofactor = 150)`

sce@int_colData contains the FSC, SSC and the three missing parameters (CD196, gdTCR and CD56)

Any ideas what I am doing wrong?

**Comment by HelenaLC** [comment]
Try running with FACS=TRUE - that should solve it. By default, non-mass channels are moved out and into the internal metadata (for CyTOF, this would e.g. be the time channel). But we don’t want that for FACS, were no channels are mass channels anyways
