### ISSUE TITLE
heatmap color change

### ISSUE THREAD

**Issue by haowBio** [markrobinsonuzh/cytofWorkflow#29]
Hi,

My data condition have three levels, how can I change the annotation bar color ?
![image](https://user-images.githubusercontent.com/72370921/179124577-5a5a16e7-e0cb-413d-9867-5c250121d912.png)
![image](https://user-images.githubusercontent.com/72370921/179124614-7196217a-f160-4338-aa23-0c5c84810a5b.png)

**Comment by markrobinsonuzh** [comment]
hi @wu1997-shu,

just so i'm clear, which function are you calling here for the heatmaps?

**Comment by markrobinsonuzh** [comment]
There is a workaround for exactly this here:
https://github.com/HelenaLC/CATALYST/issues/244
