### ISSUE TITLE
FCS files with cluster labels

### ISSUE THREAD

**Issue by juniajvs** [markrobinsonuzh/cytofWorkflow#31]
Thank you so much for this amazing workflow!

We are currently having issues with some old-school immunologists that do not believe in the credibility of the clustering function done by flowSOM and CATALYST in your workflow and want to compare the data with their manual gating. Would it be possible to get FCS files with the cluster labels given by the workflow after using the cluster() function in the single cell experiment?

**Comment by markrobinsonuzh** [comment]
I haven't needed to do this in a very long time, but `CATALYST` does have this function:

https://rdrr.io/bioc/CATALYST/man/sce2fcs.html

.. so, it should be possible. It may require manual intervention for the cluster part though. For example, to get the cluster information into the data matrix of the FCS file, you might need to  modify the `sce2fcs` steps.

Hope that helps, Mark
