### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by synatkeamsk** [markrobinsonuzh/cytofWorkflow#32]
Dear respected professors,

Hope you are well. Thanks for building CYTOF package. I am a new users of CYTOF and I have flow cytometry data for analysis with CYTOF. I went through your tutorials (https://www.bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html#data-preprocessing) and run all your provided scripts. All works. However, once it comes to all my data, I am not sure how to prepare it for CYTOF because you did not provide it in your workflow. 

In CYTOF workflow, I can use the following command to load the data, then I can run all your script. 
```
library(HDCytoData)
fs <- Bodenmiller_BCR_XL_flowSet()
``` 
I have fcs files for CYTOF, I am wondering whether you have instruction and tutorials how to prepare and load data into R so that I can replicate your scripts using my data. Sorry for the question as I am just starting to use it and find it very impressive. 
I hope you could help me. I am looking forward to your response.

Regards,
Synat

**Comment by markrobinsonuzh** [comment]
Hi @synatkeamsk,

There are instructions in the text:

---
Alternatively, the files can be downloaded manually from the [Citrus Cytobank repository](https://community.cytobank.org/cytobank/experiments/15713/download_files) and loaded into R as a flowSet using `read.flowSet()` from the [flowCore](https://bioconductor.org/packages/3.17/flowCore) package [[29](https://bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html#ref-Hahne2009)]. Importantly, `read.flowSet()` and the underlying `read.FCS()` functions, by default, may transform the marker intensities and remove cells with extreme positive values. This behavior can be controlled with arguments `transformation` and `truncate_max_range`, respectively.
---

Did you try that?

Best wishes, Mark
