### ISSUE TITLE
R session aborted

### ISSUE THREAD

**Issue by yueli8** [markrobinsonuzh/cytofWorkflow#38]
Hello,

Thank you so much for developing so nice software.

When I ran following commands, it always shows `R session aborted`.

What can I do at present stage?

Thank you in advance for your great help!

Best,

Yue

```
da_res1 <- diffcyt(sce, 
    formula = da_formula1, contrast = contrast,
    analysis_type = "DA", method_DA = "diffcyt-DA-GLMM",
    clustering_to_use = "merging1", verbose = FALSE) 
```
![Screenshot from 2024-06-21 02-27-46](https://github.com/markrobinsonuzh/cytofWorkflow/assets/40526984/c577e8f3-09b0-4ae4-9a5f-80997b27062a)

**Comment by HelenaLC** [comment]
What version of R are you using? What’s the output of your session info? Hard to advise without any information…

**Comment by yueli8** [comment]
Hello HelenaLC,

Thank you so much for your quick response!

R version is R 4.4.0.

Please see following Screenshot.

Thank you in advance for your great help!

Best,

Yue

![Screenshot from 2024-06-21 02-27-46](https://github.com/markrobinsonuzh/cytofWorkflow/assets/40526984/6315585d-9d85-4165-85cc-7ce5f662f2ec)

**Comment by markrobinsonuzh** [comment]
I'm not fully sure. But are you running this in VSCode ?

https://www.reddit.com/r/Ubuntu/comments/1d9ajpb/vscode_has_been_crashing_on_ubuntu_22044_lts_x86/

(at least several of the error message related to this are potentially VSCode-related)

**Comment by yueli8** [comment]
Hello markrobinsonuzh,

Thank you so much for your great help!

I running all these commands in R studio version 4.4.0. The environment is Ubuntu 18.04.5 LTS.

Thank you again and really appreciated!

Best,

Yue

**Comment by markrobinsonuzh** [comment]
Hi Yue,

Do you have the latest version of RStudio?

From what I've found, for example:

https://stackoverflow.com/questions/67638836/r-crashing-while-displaying-ggplot-after-update-process-memory-read-out-of-rang

https://issues.apache.org/jira/browse/ARROW-13037

I believe this is fully unrelated to `diffcyt` / `cytofWorkflow`.

Best, Mark

**Comment by yueli8** [comment]
Hello markrobinsonuzh,

Thank you so much for your quick response!

My RStudio is 4.4.0. My Ubuntu environment is 18.04.5 LTS.

Is that because my Ubuntu environment is too old ?I should upgrade my Ubuntu environment?

Thank you in advance for your great help!

Best,

Yue

**Comment by markrobinsonuzh** [comment]
Your version of R is 4.4.0, but what version of RStudio do you have? See here:
https://posit.co/download/rstudio-desktop/

In any case, Ubuntu 18.04 is "end of life" for >1 year now, so it could be useful to upgrade:
https://ubuntu.com/blog/18-04-end-of-standard-support

I will close the issue because it does not appear to be a `cytofWorkflow` issue (I also checked building it locally on my hardward and it was fine), but rather a local installation issue.
