### ISSUE TITLE
Error in md_cols while creating sce 

### ISSUE THREAD

**Issue by Sa753** [markrobinsonuzh/cytofWorkflow#7]
Dear sir,

I am always getting that error message and can't get beyond that stage. 

I ensured installing the recent version of R and CATALYST as you previously advised. Also, I am following the recent version published on 17th of Dec 2019.  but the issue unfortunately is not resolved and I can't get beyond that stage

sce <- prepData(fs, panel, md, features = panel$fcs_colname)
Error in prepData(fs, panel, md, features = panel$fcs_colname) : 
  all(ids %in% md[[md_cols$file]]) is not TRUE

I also did ensure that the md$file_names are the same as in the flowset. 

Please advise

Thanks
Samar

**Comment by markrobinsonuzh** [comment]
Can you give the output of `sessionInfo()` after loading the `CATALYST` package? As I write this, 1.10.1 is the latest version.

Also the outputs of `md` and `flowCore::keyword(fs, "FILENAME")` could be informative.

Best, Mark
