### ISSUE TITLE
Removed rows containing missing values (geom_point).

### ISSUE THREAD

**Issue by jspegarova** [markrobinsonuzh/cytofWorkflow#8]
Hi

I get the warning message below after the line 
lgd <- get_legend(p2 +                                                        
                    guides(color =  guide_legend(ncol = 2, override.aes = list(size = 3))))  

Warning message:
Removed 718647 rows containing missing values (geom_point).

Any idea of where this is coming from and how to solve it?

Thanks for your help.
J

**Comment by markrobinsonuzh** [comment]
Hard to diagnose without more details, but maybe it's actually ok as it's only a warning and maybe `p2` already makes a figure? Is it simply that you have many cells, but only calculate the tSNE projection for a small number (e.g., 500) of cells and thus the rest are NA (missing). If so, then it's not really a problem.

In general, it's best to give a reproducible example, and the output of `sessionInfo()`.

Mark

**Comment by HelenaLC** [comment]
Yes, if p2 is a dim red plot, it is most likely because the dim red was run only a subset of cells and thus contains NAs for many cells. The warning will be suppress in the next devel version as it shouldn’t be reason for concern.
